### ISSUE TITLE
Add missing top-level domains

### ISSUE THREAD

**Issue by jsf9k** [jsf9k/gatherer#52]
# 🐛 Summary #

Quite a few domains have been added to `current-federal-non-dotgov.csv` in cisagov/scan-target-data#45 and cisagov/scan-target-data#48.  Some of these domains belong to top-level domains that are not listed here:
https://github.com/cisagov/gatherer/blob/e17fdca7e5e3cf0dd56295e498480717aa59a97b/gather-domains.sh#L90
This means that those domains will not be scanned, so this must be remedied.

**Comment by climber-girl** [comment]
Good catch @jsf9k!
